spring.application.name=AplicativoWeb
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vinculacion
spring.datasource.username=postgres 
spring.datasource.password=12345678

# -Indica al controlador que permite la conexion entre Java y PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# -Traduce las consultas JPA de Java a la sintaxis de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -El update actualiza automáticamente la estructura de la base de datos
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -Evita el error de serialización
spring.jackson.serialization.fail-on-empty-beans=false